name: Create PR for Version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to create the PR from and to'
        type: string
        default: ''

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write

jobs:
  get-old-version:
    name: Create Version Bump PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Get version
        id: get-version
        run: |
          echo "version=$(cat package.json | grep '"version"' | cut -d '"' -f 4)" >> $GITHUB_OUTPUT
      - name: Bump version
        id: bump-version
        run: |
          echo "new_version=$(echo ${{ steps.get-version.outputs.version }} | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')" >> $GITHUB_OUTPUT
      - name: Update Files
        id: update-files
        run: |
          sed -i "s/${{ steps.get-version.outputs.version }}/${{ steps.bump-version.outputs.new_version }}/g" package.json
          sed -i "s/${{ steps.get-version.outputs.version }}/${{ steps.bump-version.outputs.new_version }}/g" package-lock.json
          sed -i "s/${{ steps.get-version.outputs.version }}/${{ steps.bump-version.outputs.new_version }}/g" src/wp-includes/version.php
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: ${{ github.event.inputs.branch }}
          branch-suffix: timestamp
          delete-branch: true
          commit-message: "Version bump"
          title: "Version bump from ${{ steps.get-version.outputs.version }} to ${{ steps.bump-version.outputs.new_version }}"
          body: |
            Update from ${{ steps.get-version.outputs.version }} to ${{ steps.bump-version.outputs.new_version }}
            This PR is autogenerated by the version bump workflow.
